### ISSUE TITLE
Help from Stackoverflow

### ISSUE THREAD

**Issue by QwerMike** [sekoudosso82/sekoudosso82.github.io#1]
Cannot answer the question on stackoverlow because it is [on hold]. So here I'am.
The images on your presentation do not show up because they have bad name(extension).
Only 2 images - global5.jpg, global6.jpg - have correct names.
Other images, for example, global7.JPG have name with UPPERCASE letters. So you need to check your /images folder and change name to global7.jpg and so on.

**Comment by sekoudosso82** [comment]
thanks

**Comment by QwerMike** [comment]
Your welcome)
